# Generated by Django 3.0.1 on 2020-10-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_photo', models.ImageField(upload_to='passport_data/')),
                ('passport_photo', models.ImageField(upload_to='passport_data/')),
                ('adr_photo', models.ImageField(upload_to='passport_data/')),
                ('passport_data', models.CharField(max_length=16, unique=True)),
                ('issued_by', models.CharField(max_length=100)),
                ('when_issued', models.CharField(max_length=100)),
            ],
        ),
    ]
