# Generated by Django 3.0.1 on 2020-10-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Region')),
                ('order_site_price', models.IntegerField()),
                ('order_rp_price', models.IntegerField()),
                ('order_customer_price', models.IntegerField()),
                ('order_executor_price', models.IntegerField()),
                ('rate_rp_customer', models.IntegerField()),
                ('rate_rp_executor', models.IntegerField()),
                ('rate_rp_site', models.IntegerField()),
                ('rate_first_rp_site', models.IntegerField()),
                ('rate_first_rp_customer', models.IntegerField()),
                ('executor_rate_site', models.IntegerField()),
                ('executor_rate_customer', models.IntegerField()),
                ('executor_rate_executor', models.IntegerField()),
                ('commission_site', models.IntegerField()),
                ('commission_customer', models.IntegerField()),
                ('commission_executor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='region.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
    ]
