# Generated by Django 3.0.1 on 2020-10-01 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('last_balance', models.IntegerField(default=0)),
                ('name_receiver', models.CharField(max_length=50)),
                ('calc_account', models.CharField(max_length=100, unique=True)),
                ('corr_account', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('bik', models.CharField(max_length=50, unique=True)),
                ('inn', models.CharField(max_length=50, unique=True)),
                ('bank_code', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
