# Generated by Django 3.0.1 on 2020-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bik',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='calc_account',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='corr_account',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name_receiver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
